name: animaltorch
channels:
  - plotly
  - numba
  - pytorch
  - anaconda
  - defaults
  - conda-forge
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - anyio=3.6.2=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb9d737c_2
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=22.1.0=pyh71513ae_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - blas=1.0=mkl
  - bleach=5.0.1=pyhd8ed1ab_0
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py39hb9d737c_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2024.2.2=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_1
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - colour=0.1.5=py39h06a4308_0
  - contourpy=1.0.5=py39hf939315_0
  - cryptography=38.0.2=py39hd97740a_0
  - cudatoolkit=11.6.0=hecad31d_10
  - cudnn=8.4.1.50=hed8a83a_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.3=py39h5a03fae_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - ephem=4.1.5=py39hd1e30aa_1
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h27087fc_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.9=h27cfd23_1
  - flit-core=3.7.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=hc2a2eb6_0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py39hb9d737c_0
  - freetype=2.12.1=hca18f0e_0
  - geographiclib=2.0=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.74.0=h6239696_0
  - glib-tools=2.74.0=h6239696_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - hdf5=1.10.6=h3ffc7dd_1
  - icu=58.2=hf484d3e_1000
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py39hf3d152e_0
  - importlib_resources=5.10.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.16.1=pyh210e3f2_0
  - ipython=8.4.0=py39h06a4308_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py39h06a4308_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h166bdaf_2
  - jsonschema=4.16.0=pyhd8ed1ab_0
  - jupyter_client=7.4.3=pyhd8ed1ab_0
  - jupyter_contrib_core=0.4.0=pyhd8ed1ab_0
  - jupyter_contrib_nbextensions=0.5.1=pyhd8ed1ab_2
  - jupyter_core=4.11.1=py39hf3d152e_0
  - jupyter_highlight_selected_word=0.2.0=py39hf3d152e_1005
  - jupyter_latex_envs=1.4.6=pyhd8ed1ab_1002
  - jupyter_nbextensions_configurator=0.4.1=py39hf3d152e_2
  - jupyter_server=1.21.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kaleido-core=0.2.1=h3644ca4_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py39hf939315_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.39=hc81fddc_0
  - lerc=4.0.0=h27087fc_0
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libdeflate=1.14=h166bdaf_0
  - libedit=3.1.20210910=h7f8727e_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.2=h27087fc_0
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.74.0=h7a41b64_0
  - libiconv=1.17=h166bdaf_0
  - libllvm10=10.0.1=he513fc3_3
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.38=h753d276_0
  - libpq=12.9=h16c4e8d_3
  - libsndfile=1.1.0=h27087fc_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.39.4=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.4.0=h55922b4_4
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.4=h522a892_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=14.0.4=he0ac6c6_0
  - llvmlite=0.39.1=py39he1b5a44_0
  - lxml=4.9.1=py39hb9d737c_0
  - markupsafe=2.1.1=py39hb9d737c_1
  - mathjax=2.7.7=ha770c72_3
  - matplotlib-base=3.5.3=py39h19d6b11_2
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - mpg123=1.30.2=h27087fc_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.4.5=pyhd8ed1ab_0
  - nbclient=0.5.13=pyhd8ed1ab_0
  - nbconvert=7.2.2=pyhd8ed1ab_0
  - nbconvert-core=7.2.2=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.2=pyhd8ed1ab_0
  - nbformat=5.7.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - notebook=6.5.1=pyha770c72_0
  - notebook-shim=0.2.0=pyhd8ed1ab_0
  - nspr=4.33=h295c915_0
  - nss=3.78=h2350873_0
  - numba=0.56.3=np1.16py3.9h59fbc97_g6982acdaa_0
  - numexpr=2.8.3=py39h807cd23_0
  - numpy=1.23.3=py39h14f4228_0
  - numpy-base=1.23.3=py39h31eccc5_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=1.1.1w=hd590300_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.4=py39h6a678d5_0
  - pandoc=2.19.2=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.37=hc3806b6_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py39hace64e9_1
  - pip=22.3=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - plotly=5.10.0=py_0
  - ply=3.11=py_1
  - prometheus_client=0.15.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.9.3=py39hb9d737c_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pvlib=0.10.3=pyha770c72_0
  - pvlib-python=0.10.3=hd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.7=py39h6a678d5_1
  - pyqt5-sip=12.11.0=py39h6a678d5_1
  - pyrsistent=0.18.1=py39hb9d737c_1
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pysoundfile=0.11.0=pyhd8ed1ab_0
  - python=3.9.13=h9a8a25e_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=py3.9_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=py39h06a4308_0
  - pyyaml=6.0=py39hb9d737c_4
  - pyzmq=24.0.1=py39headdf64_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_1
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.5.0=pyhd8ed1ab_0
  - sip=6.6.2=py39h5a03fae_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.39.4=h4ff8645_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.13.2=py39hd257fcd_0
  - tbb=2021.6.0=h924138e_0
  - tenacity=8.0.1=py39h06a4308_1
  - terminado=0.16.0=pyh41d4057_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - torchaudio=0.12.1=py39_cu116
  - torchvision=0.13.1=py39_cu116
  - tornado=6.2=py39hb9d737c_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=4.4.0=pyha770c72_0
  - unicodedata2=14.0.0=py39hb9d737c_1
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.1=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.5.2=py39h06a4308_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.9.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h6239696_4
  - pip:
      - absl-py==1.3.0
      - aiohttp==3.8.3
      - aiosignal==1.2.0
      - alembic==1.9.4
      - alpha-shapes==1.1.0
      - argparse==1.4.0
      - astunparse==1.6.3
      - async-timeout==4.0.2
      - autopage==0.5.1
      - backports-functools-lru-cache==1.6.4
      - boltons==21.0.0
      - cachetools==5.2.0
      - cliff==4.2.0
      - cloudpickle==2.2.1
      - cmaes==0.9.1
      - cmd2==2.4.3
      - colorlog==6.7.0
      - copulae==0.7.9
      - cpflows==0.1.2
      - cython==0.29.37
      - datasets==2.6.1
      - decorator==4.4.2
      - dill==0.3.5.1
      - evaluate==0.2.2
      - ffmpeg-python==0.2.0
      - filelock==3.8.0
      - flatbuffers==22.9.24
      - frozenlist==1.3.1
      - fsspec==2022.10.0
      - future==0.18.2
      - gast==0.4.0
      - google-auth==2.13.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - greenlet==2.0.2
      - grpcio==1.50.0
      - h3==3.7.6
      - h5py==3.7.0
      - hdbscan==0.8.33
      - huggingface-hub==0.10.1
      - imageio==2.33.1
      - imageio-ffmpeg==0.4.9
      - ipdb==0.13.13
      - jiwer==2.5.1
      - joblib==1.4.2
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - lazy-loader==0.4
      - levenshtein==0.20.2
      - libclang==14.0.6
      - mako==1.2.4
      - markdown==3.4.1
      - matplotlib==3.9.2
      - more-itertools==9.0.0
      - moviepy==1.0.3
      - multidict==6.0.2
      - multiprocess==0.70.13
      - networkx==3.2.1
      - nvidia-nccl-cu12==2.23.4
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - optuna==2.10.1
      - pbr==5.11.1
      - phdu==2.8.8
      - prettytable==3.6.0
      - proglog==0.1.10
      - protobuf==3.19.6
      - pyarrow==9.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydeprecate==0.3.2
      - pynndescent==0.5.13
      - pyperclip==1.8.2
      - pytorch-forecasting==0.10.3
      - pytorch-lightning==1.7.7
      - pytz-deprecation-shim==0.1.0.post0
      - rapidfuzz==2.11.1
      - regex==2022.9.13
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rpy2==3.5.5
      - rsa==4.9
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - seaborn==0.12.2
      - shap==0.46.0
      - shapely==2.0.2
      - sklearn==0.0
      - slicer==0.0.8
      - sqlalchemy==2.0.4
      - stevedore==5.0.0
      - subprocess32==3.5.4
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.0
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.27.0
      - termcolor==2.0.1
      - threadpoolctl==3.5.0
      - tidypath==1.5.1
      - tifffile==2024.8.30
      - timezonefinder==6.4.0
      - tokenizers==0.13.1
      - tomli==2.0.1
      - torchmetrics==0.10.0
      - torchsde==0.2.5
      - tqdm==4.64.1
      - trampoline==0.1.2
      - transformers==4.23.1
      - triangle==20230923
      - tzdata==2022.5
      - tzlocal==4.2
      - umap-learn==0.5.6
      - werkzeug==2.2.2
      - whisper==1.0
      - wrapt==1.14.1
      - xgboost==2.1.1
      - xxhash==3.1.0
      - yarl==1.8.1
